vars:
  time_limit: &time_limit 86400 # 3600 * 24 hours
  step_count: &step_count 2000 # empirically, we find that the agent does 500 steps in ~6 hours, so 2000 steps should be about right for 24 hours
  data_recursion_limit: &data_recursion_limit 512
  experiment_recursion_limit: &experiment_recursion_limit 512

scievo/gemini-low-medium:
  start: scievo/start.sh
  dockerfile: scievo/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for bench.mlebench_workflow
    data-recursion-limit: *data_recursion_limit
    experiment-recursion-limit: *experiment_recursion_limit
    models: gemini-low-medium
  env_vars:
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
    OPENHANDS_MODEL: gemini/gemini-2.5-flash

scievo/gemini-medium-high:
  start: scievo/start.sh
  dockerfile: scievo/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for bench.mlebench_workflow
    data-recursion-limit: *data_recursion_limit
    experiment-recursion-limit: *experiment_recursion_limit
    models: gemini-medium-high
  env_vars:
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
    OPENHANDS_MODEL: gemini/gemini-2.5-flash

scievo/gpt-low-medium:
  start: scievo/start.sh
  dockerfile: scievo/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for bench.mlebench_workflow
    data-recursion-limit: *data_recursion_limit
    experiment-recursion-limit: *experiment_recursion_limit
    models: gpt-low-medium
  env_vars:
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
    # OPENHANDS_MODEL: gpt-5-mini
    OPENHANDS_MODEL: gpt-5.1-codex-mini

scievo/gpt-medium-high:
  start: scievo/start.sh
  dockerfile: scievo/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for bench.mlebench_workflow
    data-recursion-limit: *data_recursion_limit
    experiment-recursion-limit: *experiment_recursion_limit
    models: gpt-medium-high
  env_vars:
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
    # OPENHANDS_MODEL: gpt-5-mini
    OPENHANDS_MODEL: gpt-5.1-codex-mini

scievo/gemini3-medium-high:
  start: scievo/start.sh
  dockerfile: scievo/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for bench.mlebench_workflow
    data-recursion-limit: *data_recursion_limit
    experiment-recursion-limit: *experiment_recursion_limit
    models: gemini3-medium-high
  env_vars:
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
    OPENHANDS_MODEL: gemini/gemini-2.5-flash